# Generated by Django 5.0.6 on 2024-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_advisor_phonenumber_alter_ask_equity_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ask',
            name='equity_share',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='creator_id',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='modifier_id',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='p_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='captable',
            name='percentage_of_shares',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='captable',
            name='shareholder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='creator_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='modifier_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='a_yearbefore_pl',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='a_yearbefore_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='competitor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_pl',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_incorporation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_pl',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='vision',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companypptandvideo',
            name='p_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingbalancesheet',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingbalancesheet',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingcashflow',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingcashflow',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingincomestatement',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingincomestatement',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan_finacials',
            name='p_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productsandservices',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
