# Generated by Django 5.0.6 on 2024-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='phonenumber',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='ask',
            name='equity_share',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='creator_id',
            field=models.CharField(max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='modifier_id',
            field=models.CharField(max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='current_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='debt_capital_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='debt_equity_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='debt_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='debt_service_coverage_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='equity_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='operating_cash_flow_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetratios',
            name='working_capital',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='p_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='captable',
            name='percentage_of_shares',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='captable',
            name='shareholder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='creator_id',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='modifier_id',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowratios',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowratios',
            name='current_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowratios',
            name='debt_service_coverage_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowratios',
            name='operating_cash_flow_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowratios',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowratios',
            name='working_capital',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='company',
            name='a_yearbefore_pl',
            field=models.DecimalField(decimal_places=2, max_digits=210, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='a_yearbefore_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=210, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(max_length=21010, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='competitor',
            field=models.CharField(max_length=21010, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_pl',
            field=models.DecimalField(decimal_places=2, max_digits=210, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=210, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_incorporation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_pl',
            field=models.DecimalField(decimal_places=2, max_digits=210, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=210, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.CharField(max_length=21010, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=21010, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='vision',
            field=models.CharField(max_length=21010, null=True),
        ),
        migrations.AlterField(
            model_name='companypptandvideo',
            name='p_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingbalancesheet',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingbalancesheet',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingcashflow',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingcashflow',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingincomestatement',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingincomestatement',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='debt_service_coverage_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='earnings_per_share',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='ebitda_margin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='gross_profit_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='interest_service',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='net_profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='operating_cash_flow_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementratios',
            name='operating_profit_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan_finacials',
            name='p_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsandservices',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=2100),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator_id',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='team',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
