# Generated by Django 5.0.6 on 2024-10-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_advisor_phonenumber_alter_ask_equity_share_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
