# Generated by Django 5.0.6 on 2024-10-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField(default=None, null=True)),
                ('line_no', models.IntegerField(default=None, null=True)),
                ('summary', models.TextField()),
                ('link', models.CharField(default=None, max_length=50, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
