# Generated by Django 5.0.6 on 2024-10-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_benchmark_bench_mark_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='equity_share',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
