# Generated by Django 5.0.6 on 2024-10-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_ask_equity_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_finacials',
            name='p_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.productsandservices'),
        ),
    ]
