# Generated by Django 5.0.6 on 2024-10-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_valuation_valuationdocument_delete_benchmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypptandvideo',
            name='p_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.productsandservices'),
        ),
        migrations.AlterField(
            model_name='valuationdocument',
            name='valuation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.valuation'),
        ),
    ]
