# Generated by Django 5.0.6 on 2024-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_companypptandvideo_p_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypptandvideo',
            name='p_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
